---
# BEGIN
spring:
  output:
    ansi:
      enabled:

server:
  port: 7070
# END

users:
  admins:
    emails:
      - gjoinsey1@blogger.com
      - scrosi4@cam.ac.uk
      - brundle@cam.ac.uk
    names:
      - Emmit Brundle
      - Glynn Joinsey
      - Sarina Crosi